### ISSUE TITLE
first character can be anything, dont hard code it to 'a'. = Please check the updated code

### ISSUE THREAD

**Issue by jeetendrabhattad** [ChaitanyaDeshpandePY/python#3]
https://github.com/ChaitanyaDeshpandePY/python/blob/a3a1bba2b89a33b1b0b981e8b8fba37808a28ec7/python_exercises_september_2018/star_replace_in_string.py#L18

**Comment by ChaitanyaDeshpandePY** [comment]
Will check

**Comment by ChaitanyaDeshpandePY** [comment]
Please check the updated code
